version: '3.3'

services:
  service_author:
    build: 
      context: service_author
      dockerfile: Dockerfile
    container_name: service_author
    networks:
      - arch-network    
    ports:
      - 8081:8081

  service_presentation:
    build:
      context: service_presentation
      dockerfile: Dockerfile
    container_name: service_presentation
    networks:
      - arch-network
    ports:
      - 8082:8082

  service_main:
    build:
      context: service_main
      dockerfile: Dockerfile
    container_name: service_main
    depends_on:
      - service_presentation
      - service_author
    networks:
      - arch-network
    ports:
      - 8083:8083


      
networks:
  arch-network:
    ipam:
      driver: default
      config:
        - subnet: "172.23.200.0/24"
