openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Conference server API'
  description: API to retrive information about main entities of Conference server
servers:
  - url: http://localhost:8081

paths:
  /authors/{author_id}:
    get:
      summary: Read a author
      parameters:
      - name: author_id
        description: The unique identifier of the author
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/Author_id'
      responses:
        200:
          description: Conference author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  
 
components:
  schemas:
    Author_id:
      description: The unique identifier of author
      type: string

    Author:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Author_id'
        birth_date:
          type: string
        title:
          type: string
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string

    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string